package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class NavigatorBarPanel extends JPanel {
    RoundedButton homeButton;
    RoundedButton backButton;
    JLabel pathLabel;
    Constraints constraints;

    public NavigatorBarPanel(ArrayList<JFrame> callingFrames) {
        super();

        constraints = new Constraints();
        this.setLayout(new FlowLayout(FlowLayout.LEFT));
        this.setBackground(Color.white);

        this.setHomeButton(callingFrames);
        this.setBackButton(callingFrames);
        this.setPath(callingFrames);
    }

    private void setHomeButton(ArrayList<JFrame> callingFrames) {
        homeButton = new RoundedButton("Home");
        //homeButton.setLayout (new FlowLayout ());
        homeButton.setFocusable(false);

        homeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                for (int i = callingFrames.size() - 2; i > 1; i--) {
                    callingFrames.get(i).dispose();
                    callingFrames.remove(i);
                }

                callingFrames.get(1).setVisible(true);
                if (callingFrames.size() > 2) {
                    JFrame tmp = callingFrames.getLast();
                    callingFrames.removeLast();
                    tmp.dispose();
                }
            }
        });

        constraints.setConstraints(0, 0, 1, 1, GridBagConstraints.VERTICAL,
                0, 0, GridBagConstraints.LINE_START);
        this.add(homeButton, constraints.getConstraints());
        //constraints.setConstraints (0, 0, 1, 1, GridBagConstraints.VERTICAL, 0, 0, GridBagConstraints.LINE_START);
        this.add(homeButton);
        homeButton.setVisible(true);
    }

    private void setBackButton(ArrayList<JFrame> callingFrames) {
        backButton = new RoundedButton("Back");
        //backButton.setLayout (new GridBagLayout ());
        backButton.setFocusable(false);

        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                callingFrames.get(callingFrames.size() - 2).setVisible(true);
                JFrame tmp = callingFrames.getLast();
                callingFrames.removeLast();
                tmp.dispose();
            }
        });

        constraints.setConstraints(1, 0, 1, 1, GridBagConstraints.VERTICAL,
                0, 0, GridBagConstraints.LINE_START);
        this.add(backButton, constraints.getConstraints());
        //constraints.setConstraints (1, 0, 1, 1, GridBagConstraints.VERTICAL, 0, 0, GridBagConstraints.LINE_START);
        this.add(backButton);
        backButton.setVisible(true);
    }

    private void setPath(ArrayList<JFrame> callingFrames) {
        String path = "Posizione:\"";
        for (int i = 1; i < callingFrames.size(); i++) {
            path += callingFrames.get(i).getTitle() + "/";
        }
        path += "\"";
        pathLabel = new JLabel(path);

        //pathLabel.setLayout (new GridBagLayout ());

        //constraints.setConstraints (2, 0, 17, 1, GridBagConstraints.BOTH, 0, 0, GridBagConstraints.LINE_START);
        this.add(pathLabel);
        pathLabel.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
