package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class NewLoginScreen {
    private JFrame mainFrame;

    //Padding Panels
    private JFrame topPadding;
    private JFrame bottomPadding;
    private JFrame leftPadding;
    private JFrame rightPadding;

    private Constraints constraints;
    private static Controller controller;

    public NewLoginScreen(ArrayList<JFrame> callingFrames, Controller controller) {

        constraints = new Constraints();

        this.setMainframe(callingFrames, controller);

        this.addPadding();
    }

    public static void main(String[] args) {
        new NewLoginScreen(new ArrayList<JFrame>(), new Controller());
    }

    private void setMainframe(ArrayList<JFrame> callingFrames, Controller controller) {
        mainFrame = new JFrame("Log In");
        callingFrames.addLast(mainFrame);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainFrame.setLayout(new GridBagLayout());
        mainFrame.setSize(1080, 720);

        if (controller.developerMode) mainFrame.setBackground(Color.YELLOW);
    }

    private void addPadding() {
        int w, h;
        w = mainFrame.getWidth();
        h = mainFrame.getHeight();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
