package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class PassengerPanelAdmin extends PassengerPanel {

    private JCheckBox checkinCheckBox;

    public PassengerPanelAdmin(Controller controller, List<PassengerPanel> passengerPanelsAdmin, List<Integer> bookedSeats) {

        super(controller, passengerPanelsAdmin, bookedSeats);
    }

    @Override
    public void addCheckinCheckBox (boolean flag) {
        checkinCheckBox = new JCheckBox("Checkin", flag);

        constraints.setConstraints(0, 3, 3, 1,
                GridBagConstraints.NONE, 0, 0, GridBagConstraints.CENTER);
        this.add(checkinCheckBox, constraints.getGridBagConstraints());
        checkinCheckBox.setVisible(true);
    }

    public JCheckBox getCheckinCheckBox () {
        return checkinCheckBox;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
