package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class RemoveLuggageButton extends JButton {
    private int index;
    private Constraints constraints;

    public RemoveLuggageButton(Controller controller, ArrayList<LuggagePanel> luggagePanels,
                               ArrayList<RemoveLuggageButton> removeLuggageButtons, JPanel luggagesPanel, JScrollPane scrollPane, int i) {
        super("Rimuovi ");
        index = i;
        constraints = new Constraints();

        this.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //creo variabili temporanee
                LuggagePanel tmpluggagePanel = luggagePanels.get(index);
                RemoveLuggageButton tmpremoveLuggageButton = removeLuggageButtons.get(index);
                tmpluggagePanel.setVisible(false);
                tmpremoveLuggageButton.setVisible(false);

                //rimuovo da liste
                luggagePanels.remove(index);
                removeLuggageButtons.remove(index);

                //rimuovo da pagina
                luggagesPanel.remove(tmpluggagePanel);
                luggagesPanel.remove(tmpremoveLuggageButton);

                //aggiusto la pagina
                for (int i = index; i < luggagePanels.size(); i++) {
                    luggagesPanel.remove(luggagePanels.get(i));
                    constraints.setConstraints(0, i, 1, 1,
                            GridBagConstraints.NONE, 0, 0, GridBagConstraints.LINE_END);
                    luggagesPanel.add(luggagePanels.get(i), constraints.getConstraints());
                    luggagePanels.get(i).setVisible(true);

                    luggagesPanel.remove(removeLuggageButtons.get(i));
                    constraints.setConstraints(1, i, 1, 1,
                            GridBagConstraints.NONE, 0, 0, GridBagConstraints.LINE_START);
                    luggagesPanel.add(removeLuggageButtons.get(i), constraints.getConstraints());
                    removeLuggageButtons.get(i).setVisible(true);

                    removeLuggageButtons.get(i).index--;
                }

                //aggiusto view
                scrollPane.setViewportView(luggagesPanel);
            }
        });
    }

    public void decreaseIndex() {
        index--;
    }

    public int getIndex() {
        return index;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
